dataset: MovieLense10M

batch_size: 4096

num_factors: 32
dropout: 0.05

lr: 1e-2
bias_weight_decay: 1e-5
embd_weight_decay: 1e-5
step_size: 30

min_rating: 0.5
max_rating: 5

epoch: 120

reproducibility:
  fix_rng: true
  seed: 1000
