defaults:
  - _self_
  - main: ml-100k
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  job_logging:
    handlers:
      file:
        filename: /dev/null
  output_subdir: null
  run:
    dir: .
  job:
    chdir: false
